### ISSUE TITLE
when exporting csv, translate selected class to be human-readable

### ISSUE THREAD

**Issue by Chovin** [Tropicode-Guam/gymjim#45]
<img width="166" alt="image" src="https://github.com/Tropicode-Guam/gymjim/assets/17536161/7f7b81ad-e8f3-49fe-9660-86f69832e0d1">

instead, should name the filename to be the class name

**Comment by Chovin** [comment]
oh, I misunderstood what the export button does. it shouldn't export all the classes, rather there should be an export button per class and there should probably be an option to choose what day to export / print

**Comment by Chovin** [comment]
maybe keep this option and just add a per class per day option. ask Hilton if they want a printout of the signups per class per day also so that the instructor can see the list

**Comment by bubbapang** [comment]
so status rn is "ask hilton if they want a more specific option"

**Comment by Chovin** [comment]
this was fixed awhile ago
