### ISSUE TITLE
styling / UX (each checkbox a commit)

### ISSUE THREAD

**Issue by bubbapang** [Tropicode-Guam/gymjim#99]
EASY
- [x] better spacing (admin)
- [x] better sequence of components (admin)
- [x] h1 directive (like pinterest) (make bold)
- [x] edges rounded on class cards
- [x] twittter style dont take up the whole screen

MEDIUM
- [x] colors on the classes cards (from preset pallette) color coding for the classes
- [x] hilton branding top left (make white logo black)
- [x] dropdown for insurance (include other/guest)

HARD
- [x] cardify the admin panel (add class + class list)

**Comment by Chovin** [comment]
@bubbapang what does h1 directive mean? I made them bold, is that it?

**Comment by Chovin** [comment]
@bubbapang we already do the twitter style thing, did you want to adjust the max-width?

**Comment by bubbapang** [comment]
1) like this: 
![image](https://github.com/Tropicode-Guam/gymjim/assets/49807160/b29c6577-b046-4f5f-a6a9-bff4a8b82d7a)

2) i want margins on the side like twitter, to tighten up the landing page, and put a subtle divider (border color)

**Comment by bubbapang** [comment]
like "Start Your Fitness Journey Today With Our Specialized Classes"

**Comment by bubbapang** [comment]
- [ ] also make cards bigger, more rounded, more image, less text

**Comment by bubbapang** [comment]
- [ ] make the hilton logo have its own bar, so it wont cover text
